Heroku seems to have difficulty building with SBT v0.13.9
```
-----> Play 2.x - Scala app detected
-----> Installing OpenJDK 1.8... done
-----> Running: sbt compile stage
       Downloading sbt launcher for 0.13.9:
         From  http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.9/sbt-launch.jar
           To  /tmp/scala_buildpack_build_dir/.sbt_home/launchers/0.13.9/sbt-launch.jar
       Getting org.scala-sbt sbt 0.13.9 ...
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.9/jars/sbt.jar ...
       	[SUCCESSFUL ] org.scala-sbt#sbt;0.13.9!sbt.jar (2336ms)
       downloading https://jcenter.bintray.com/org/scala-lang/scala-library/2.10.5/scala-library-2.10.5.jar ...
       	[SUCCESSFUL ] org.scala-lang#scala-library;2.10.5!scala-library.jar (3956ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.9/jars/main.jar ...
       	[SUCCESSFUL ] org.scala-sbt#main;0.13.9!main.jar (2977ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.9/jars/compiler-interface-src.jar ...
       	[SUCCESSFUL ] org.scala-sbt#compiler-interface;0.13.9!compiler-interface-src.jar (1176ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.9/jars/compiler-interface-bin.jar ...
       	[SUCCESSFUL ] org.scala-sbt#compiler-interface;0.13.9!compiler-interface-bin.jar (1008ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/precompiled-2_8_2/0.13.9/jars/compiler-interface-bin.jar ...
       	[SUCCESSFUL ] org.scala-sbt#precompiled-2_8_2;0.13.9!compiler-interface-bin.jar (5660ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/precompiled-2_9_2/0.13.9/jars/compiler-interface-bin.jar ...
       	[SUCCESSFUL ] org.scala-sbt#precompiled-2_9_2;0.13.9!compiler-interface-bin.jar (3898ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/precompiled-2_9_3/0.13.9/jars/compiler-interface-bin.jar ...
       	[SUCCESSFUL ] org.scala-sbt#precompiled-2_9_3;0.13.9!compiler-interface-bin.jar (3538ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/actions/0.13.9/jars/actions.jar ...
       	[SUCCESSFUL ] org.scala-sbt#actions;0.13.9!actions.jar (4326ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main-settings/0.13.9/jars/main-settings.jar ...
       	[SUCCESSFUL ] org.scala-sbt#main-settings;0.13.9!main-settings.jar (6725ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/interface/0.13.9/jars/interface.jar ...
       	[SUCCESSFUL ] org.scala-sbt#interface;0.13.9!interface.jar (6009ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io/0.13.9/jars/io.jar ...
       	[SUCCESSFUL ] org.scala-sbt#io;0.13.9!io.jar (6258ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/ivy/0.13.9/jars/ivy.jar ...
       	[SUCCESSFUL ] org.scala-sbt#ivy;0.13.9!ivy.jar (5525ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logging/0.13.9/jars/logging.jar ...
       	[SUCCESSFUL ] org.scala-sbt#logging;0.13.9!logging.jar (5349ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logic/0.13.9/jars/logic.jar ...
       	[SUCCESSFUL ] org.scala-sbt#logic;0.13.9!logic.jar (4696ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/process/0.13.9/jars/process.jar ...
       	[SUCCESSFUL ] org.scala-sbt#process;0.13.9!process.jar (3202ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/run/0.13.9/jars/run.jar ...
       	[SUCCESSFUL ] org.scala-sbt#run;0.13.9!run.jar (8613ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/command/0.13.9/jars/command.jar ...
       	[SUCCESSFUL ] org.scala-sbt#command;0.13.9!command.jar (4559ms)
       downloading https://jcenter.bintray.com/org/scala-sbt/launcher-interface/1.0.0-M1/launcher-interface-1.0.0-M1.jar ...
       	[SUCCESSFUL ] org.scala-sbt#launcher-interface;1.0.0-M1!launcher-interface.jar (1379ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classpath/0.13.9/jars/classpath.jar ...
       	[SUCCESSFUL ] org.scala-sbt#classpath;0.13.9!classpath.jar (2665ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/completion/0.13.9/jars/completion.jar ...
       	[SUCCESSFUL ] org.scala-sbt#completion;0.13.9!completion.jar (2536ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/api/0.13.9/jars/api.jar ...
       	[SUCCESSFUL ] org.scala-sbt#api;0.13.9!api.jar (2739ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.9/jars/compiler-ivy-integration.jar ...
       	[SUCCESSFUL ] org.scala-sbt#compiler-ivy-integration;0.13.9!compiler-ivy-integration.jar (1791ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/relation/0.13.9/jars/relation.jar ...
       	[SUCCESSFUL ] org.scala-sbt#relation;0.13.9!relation.jar (1770ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/task-system/0.13.9/jars/task-system.jar ...
       	[SUCCESSFUL ] org.scala-sbt#task-system;0.13.9!task-system.jar (1823ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tasks/0.13.9/jars/tasks.jar ...
       	[SUCCESSFUL ] org.scala-sbt#tasks;0.13.9!tasks.jar (836ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tracking/0.13.9/jars/tracking.jar ...
       	[SUCCESSFUL ] org.scala-sbt#tracking;0.13.9!tracking.jar (6846ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/testing/0.13.9/jars/testing.jar ...
       	[SUCCESSFUL ] org.scala-sbt#testing;0.13.9!testing.jar (3293ms)
       downloading https://jcenter.bintray.com/org/scala-lang/scala-compiler/2.10.5/scala-compiler-2.10.5.jar ...
       	[SUCCESSFUL ] org.scala-lang#scala-compiler;2.10.5!scala-compiler.jar (8122ms)
       downloading https://jcenter.bintray.com/org/scala-lang/scala-reflect/2.10.5/scala-reflect-2.10.5.jar ...
       	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.10.5!scala-reflect.jar (6361ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.9/jars/control.jar ...
       	[SUCCESSFUL ] org.scala-sbt#control;0.13.9!control.jar (5303ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/collections/0.13.9/jars/collections.jar ...
       	[SUCCESSFUL ] org.scala-sbt#collections;0.13.9!collections.jar (3487ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.9/jars/compile.jar ...
       	[SUCCESSFUL ] org.scala-sbt#compile;0.13.9!compile.jar (2488ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cross/0.13.9/jars/cross.jar ...
       	[SUCCESSFUL ] org.scala-sbt#cross;0.13.9!cross.jar (1699ms)
       downloading https://jcenter.bintray.com/org/scala-sbt/ivy/ivy/2.3.0-sbt-c5d1b95fdcc1e1007740ffbecf4eb07abc51ec93/ivy-2.3.0-sbt-c5d1b95fdcc1e1007740ffbecf4eb07abc51ec93.jar ...
       	[SUCCESSFUL ] org.scala-sbt.ivy#ivy;2.3.0-sbt-c5d1b95fdcc1e1007740ffbecf4eb07abc51ec93!ivy.jar (5049ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classfile/0.13.9/jars/classfile.jar ...
       	[SUCCESSFUL ] org.scala-sbt#classfile;0.13.9!classfile.jar (1308ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cache/0.13.9/jars/cache.jar ...
       	[SUCCESSFUL ] org.scala-sbt#cache;0.13.9!cache.jar (1013ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/test-agent/0.13.9/jars/test-agent.jar ...
       	[SUCCESSFUL ] org.scala-sbt#test-agent;0.13.9!test-agent.jar (1079ms)
       downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.9/jars/apply-macro.jar ...
       	[SUCCESSFUL ] org.scala-sbt#apply-macro;0.13.9!apply-macro.jar (1025ms)

       :: problems summary ::
       :::: WARNINGS
       		module not found: org.scala-sbt#compiler-integration;0.13.9

       	==== local: tried

       	  /tmp/scala_buildpack_build_dir/.sbt_home/.ivy2/local/org.scala-sbt/compiler-integration/0.13.9/ivys/ivy.xml

       	  -- artifact org.scala-sbt#compiler-integration;0.13.9!compiler-integration.jar:

       	  /tmp/scala_buildpack_build_dir/.sbt_home/.ivy2/local/org.scala-sbt/compiler-integration/0.13.9/jars/compiler-integration.jar

       	==== jcenter: tried

       	  https://jcenter.bintray.com/org/scala-sbt/compiler-integration/0.13.9/compiler-integration-0.13.9.pom

       	  -- artifact org.scala-sbt#compiler-integration;0.13.9!compiler-integration.jar:

       	  https://jcenter.bintray.com/org/scala-sbt/compiler-integration/0.13.9/compiler-integration-0.13.9.jar

       	==== typesafe-ivy-releases: tried

       	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-integration/0.13.9/ivys/ivy.xml

       	==== Maven Central: tried

       	  https://repo1.maven.org/maven2/org/scala-sbt/compiler-integration/0.13.9/compiler-integration-0.13.9.pom

       	  -- artifact org.scala-sbt#compiler-integration;0.13.9!compiler-integration.jar:

       	  https://repo1.maven.org/maven2/org/scala-sbt/compiler-integration/0.13.9/compiler-integration-0.13.9.jar

       		::::::::::::::::::::::::::::::::::::::::::::::

       		::          UNRESOLVED DEPENDENCIES         ::

       		::::::::::::::::::::::::::::::::::::::::::::::

       		:: org.scala-sbt#compiler-integration;0.13.9: not found

       		::::::::::::::::::::::::::::::::::::::::::::::


       :::: ERRORS
       	SERVER ERROR: Internal Server Error url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-integration/0.13.9/ivys/ivy.xml


       :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
       unresolved dependency: org.scala-sbt#compiler-integration;0.13.9: not found
       Error during sbt execution: Error retrieving required libraries
         (see /tmp/scala_buildpack_build_dir/.sbt_home/boot/update.log for complete log)
       Error: Could not retrieve sbt 0.13.9
 !     ERROR: Failed to run sbt!
       We're sorry this build is failing! If you can't find the issue in application
       code, please submit a ticket so we can help: https://help.heroku.com
       You can also try reverting to the previous version of the buildpack by running:
       $ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-scala#previous-version

       Thanks,
       Heroku
 !     Push rejected, failed to compile Play 2.x - Scala app
```